### ISSUE TITLE
cant launch run_analyzer.cmd

### ISSUE THREAD

**Issue by Leroivert** [klayveR/python-poe-timeless-jewel#4]
gives me this:

> Traceback (most recent call last):
>   File "scripts/analyzer.py", line 1, in <module>
>     from ocr import OCR
>   File "D:\downloaded\timeless jewel extractor\python-poe-timeless-jewel-master\scripts\ocr.py", line 1, in <module>
>     import cv2
> ImportError: No module named cv2

**Comment by klayver** [comment]
Please execute `install.cmd` to install the necessary Python modules.
